apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: ClusterIP      # internal only inside Kubernetes cluster
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 8080        # internal service port
      targetPort: 8080
